// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDar45zlyKe_ohanwYr2FQ-TQLC-T2CDw8',
    appId: '1:1093240575614:web:acf88a36deb62b232daa2f',
    messagingSenderId: '1093240575614',
    projectId: 'camerapushnotification-a19d6',
    authDomain: 'camerapushnotification-a19d6.firebaseapp.com',
    storageBucket: 'camerapushnotification-a19d6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe4HuK1MA_cxuvdFqz_tF79QfJlGqC70A',
    appId: '1:1093240575614:android:42406c29c208eec52daa2f',
    messagingSenderId: '1093240575614',
    projectId: 'camerapushnotification-a19d6',
    storageBucket: 'camerapushnotification-a19d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Kk2o5JiIX224XFT1l1NwBo2EgcHnd5Y',
    appId: '1:1093240575614:ios:3e12915e12fb67682daa2f',
    messagingSenderId: '1093240575614',
    projectId: 'camerapushnotification-a19d6',
    storageBucket: 'camerapushnotification-a19d6.appspot.com',
    iosBundleId: 'com.example.cameraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0Kk2o5JiIX224XFT1l1NwBo2EgcHnd5Y',
    appId: '1:1093240575614:ios:95fbcee4dce408b72daa2f',
    messagingSenderId: '1093240575614',
    projectId: 'camerapushnotification-a19d6',
    storageBucket: 'camerapushnotification-a19d6.appspot.com',
    iosBundleId: 'com.example.cameraApp.RunnerTests',
  );
}
